import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@/src/font/customFont.css";
import Header from "@/src/components/layout/Header";
import { ThemeProvider } from "@/src/components/ui/theme-provider"
import { Toaster } from 'react-hot-toast'
import { ModeToggle } from "../components/ui/dark-modeButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider 
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange>
              <Toaster reverseOrder={true} position="top-center" />
              <Header />
              {children}
              <div className="fixed bottom-5 right-5"><ModeToggle/></div>
        </ThemeProvider>
      </body>
    </html>
  );
}
